### ISSUE TITLE
Xamarin Studio support for Mac

### ISSUE THREAD

**Issue by mojics** [XamFormsExtended/Xfx.Controls#14]
Opening the project on Mac Xamarin Studio shows an error of "Project does not support framework '.NETPortable,Version=v5.0'"

## Bug 

* Device Tested On: Xamarin Studio for Mac

### Expected Behavior
It should open the project normally

### Actual Behavior
Shows an error : Project does not support framework '.NETPortable,Version=v5.0'

### Steps to reproduce the Behavior
By opening the project solution

**Comment by ChaseFlorell** [comment]
<img width="1243" alt="screen shot 2017-05-11 at 6 53 44 pm" src="https://cloud.githubusercontent.com/assets/471626/25979111/4ab2bb7a-367b-11e7-9fa7-b89875b7f22b.png">

**Comment by ChaseFlorell** [comment]
Fixed in fef38f3
