### ISSUE TITLE
Can't set x:Name property to xfx Combobox

### ISSUE THREAD

**Issue by e-nathan** [XamFormsExtended/Xfx.Controls#16]
## Bug 

* Version Number of Control: 1.0.4
* Device Tested On: YU Yuphoria
* Xamarin Forms Version: 2.3.3.193
* Simulator Tested On:

### Expected Behavior

Set x:Name property to Combobox, so I can access the control in the codebehind xaml.cs page.

### Actual Behavior

Setting `x:Name` property results in the following error

`_Error: Sampling.Home.xaml.g.cs: error CS0400: The type or namespace name 'Xfx' could not be found in the global namespace (are you missing an assembly reference?)_`

## Feature Request:
Please fill in what you would like

**Comment by jhonatanfernando** [comment]
Same error here, any news?

**Comment by ChaseFlorell** [comment]
I cannot reproduce this. Can you please send me a repro?

**Comment by ChaseFlorell** [comment]
I tested again to reproduce this error and could not. If you continue to have this issue, please re-open this ticket and include a reproduction either via ZIP or in a github repo.
