### ISSUE TITLE
Changing/Updating Itemsource at Runtime

### ISSUE THREAD

**Issue by Thavudu** [XamFormsExtended/Xfx.Controls#24]
How can I change the Itemsource property in Runtime? I am fixing threshold in xamal to 8, When the selected item text reached 7; I want to change the Itemsource. Based on the new Itemsource the algorithm should be executed and show the result. Is't possible with this plugin?

**Comment by ChaseFlorell** [comment]
This is addressed in #23 if I'm reading this correctly. If you want to fully update the items source, you just set it in your code behind.

**Comment by Thavudu** [comment]
@ChaseFlorell  Thank you for helping me. I have tried and changed the complete datasource at runtime, but still suggestions are not being shown. below is the code.


**Xaml**
<xfx:XfxComboBox x:Name="cmbText"  Text="{Binding SelectedName}"
                             ItemsSource="{Binding SuggestionItemSource}"
                              SortingAlgorithm="{Binding SortingAlgorithm}" WidthRequest="300" Threshold="9"  />


**ViewModel**

When the text of combo box reaches 6 characters, I am recreating my suggestionItemSource. Below method is called properly and StringSuggestionItemSource is populating with new data properly.

 public void MyViewModel_PropertyChanged(object sender, PropertyChangedEventArgs e)
        {
            if (e.PropertyName == "SelectedName")
            {
                if (this.SelectedName.Length==6 )
                {
                    this.StringSuggestionItemSource.Clear();
                    StringSuggestionItemSource = new ObservableCollection<string>( buildPatientSearchItemSource(SuggestionItemSource));
                  
                }

            }
        }

But still new suggestion are being shown :(. 

StringSuggestionItemSource -> I am raising OnPropertyChanged event also when this property is updated.



**Algorithm**
public Func<string, ICollection<string>, ICollection<string>> SortingAlgorithm { get; } =
          (text, values) => values
              .Where(x => x.ToLower().Contains(text.ToLower())).Select(x=>x)
              .OrderBy(x => x)
              .ToList();
