### ISSUE TITLE
Wrong position in iphone but proper in android.

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [XamFormsExtended/Xfx.Controls#26]
![image](https://user-images.githubusercontent.com/16798757/31607450-ffd3c578-b289-11e7-9e08-f6647727ee43.png)

1.This is happening only in ios. Tried with iphone 6, 7plus and X..Same issue on all devices. 
2.When I rotate, text is not shown and I think it's moving towards left and cutting at edges(Tested in 6 and 7 plus real devices). 

![image](https://user-images.githubusercontent.com/16798757/31607742-20b1df4a-b28b-11e7-9aff-2264f0a112d6.png)

**Comment by ChaseFlorell** [comment]
This is related to #25
