### ISSUE TITLE
Entry's FontSize is ignored

### ISSUE THREAD

**Issue by toverux** [XamFormsExtended/Xfx.Controls#27]
## Bug 

* Version Number of Control: 1.0.4
* Device Tested On: Android 6 API 23
* Simulator Tested On: Default Android Emulator

### Expected Behavior

FontSize sets the size of the text in the input.

### Actual Behavior

FontSize is ignored.

![image](https://user-images.githubusercontent.com/1343250/31652317-f5df077c-b31e-11e7-87c5-dcfe0d5877ab.png)

Also, notice that on the last example, the bottom line of the input touches the text. So FontSize seems to have some kind of effect, but not as much as expected xD

### Steps to reproduce the Behavior

```xaml
<Entry Placeholder="Entry (FontSize=8)" FontSize="8" />
<xfx:XfxEntry Placeholder="XfxEntry (FontSize=8)" FontSize="8" />
<xfx:XfxEntry Placeholder="XfxEntry (FontSize=2)" FontSize="2" />
```

Thanks for your work!

**Comment by ChaseFlorell** [comment]
The problem here is that the Hint text is not being obeyed.

**Comment by ChaseFlorell** [comment]
Fixed in the develop branch

**Comment by brux88** [comment]
hi, but this fix is include in versione 1.1.1 in nuget?

**Comment by ChaseFlorell** [comment]
> hi, but this fix is include in versione 1.1.1 in nuget?
It is now, yes.

**Comment by brux88** [comment]
i tried on android  but not work

**Comment by ChaseFlorell** [comment]
Set the FontSize. The Hint will now match the Text size.
