### ISSUE TITLE
How to pass selected id which is not shown to the user but used for other purposes(to save to db) behind the scenes

### ISSUE THREAD

**Issue by avinashramireddy-rapidd** [XamFormsExtended/Xfx.Controls#29]
Hi,
This is very very useful plugin in all XAMARIN FORMS plugins so far. 

I have question and stuck with this for a while.

![image](https://user-images.githubusercontent.com/16798757/31658874-f4aa4cd2-b34f-11e7-8f4b-5c7f39b94008.png)

here item source return type has hardcoded List of **string** but I want to select id for the selected item

I see that there is selected item property.
But how do I set my list to contain id and value pair in first place but not show Id on the screen.

I tried following way to set but not succesful with the approach.

   ```
public class SelectList<T>
    {
        public T Value { get; set; }

        public string Text { get; set; }

        public string[] ValueText => (Value + "|" + Text).Split('|');

        public string GetSelectValue => ValueText[0];
        public string GetSelectedText => ValueText[1];
    }
   
    public List<SelectList<Guid>> GetData()
    {
    //return data here
    }

    public MainPageViewModel()
    {
      var data=GetData(); 
       var names =data.Select(n => n.GetSelectedText);

        //NamesSuggestions.ReplaceRange(data) ; 
           NamesSuggestions.ReplaceRange(names) ;

       //In above line,I want to replace entire list with type SelectList<Guid> rather than just list of strings 
      //and show only names on the page. 
      //When selected from the list I want to pass the object but  how do I set the entire object. 
    }

    public ObsColl<string> NamesSuggestions { get; } = new ObsColl<string>();
   //public ObsColl<SelectList<Guid>> ObsColl{ get; } = new ObsColl<SelectList<Guid>>();

  where ObsColl is short form of ObservableRangeCollection(using James MVVM helpers plugin)
```

I need to look in selectedItem property(not sure at this stage)

My goal is to make this generic so that I can get and set dynamic objects(for reusability on different types)
Ex:I can have list to show top 10 people and I don't know whether depending on index is suitable for my needs in future or not.

Work around is also Ok but looking for better way. 

Any help is appreciated.

**Comment by ChaseFlorell** [comment]
We use ObservableCollection and subscribe to the `ItemSelected` event.

The `ItemSelected` event contains a `SelectedItemChangedEventArgs` parameter and you can access the result with

`e.SelectedItem.ToString();`

**Comment by avinashramireddy-rapidd** [comment]
I will try when I am free this and in the mean time can u provide sample or just add things to my code mentioned above(helps to understand and do it quickly)

**Comment by ChaseFlorell** [comment]
@avinashramireddy-rapidd I've just made a commit to demonstrate how it's done.

You can either use the event `ItemSelected` and capture it in your codebehind, or you can bind a property to the `SelectedItem` property, and view it from your ViewModel.

https://github.com/XamFormsExtended/Xfx.Controls/commit/332ca2a8ac9744c3fb64def78267786026118018
