### ISSUE TITLE
After updating XCode 9 Xfx.ComboBox stops working.

### ISSUE THREAD

**Issue by NageshDegil** [XamFormsExtended/Xfx.Controls#30]
## Bug 

* Version Number of Control: 1.0.4
* Device Tested On: 
* Simulator Tested On: iPhone 8 Simulator
![unnamed 1](https://user-images.githubusercontent.com/26921042/32095252-2c11dd3e-bb20-11e7-82e7-7d3b487ecf9b.png)

I my case I have 2 Xamarin Pages, on first page when I click on button user wants to navigate to next Page which contains Pin code Combo Box (Below is the code for used ComboBox)
```
                        <StackLayout Orientation="Vertical" Spacing="2">
                            <StackLayout Orientation="Horizontal" Spacing="0" Padding="4,0">
                                <Label TextColor="Gray" Text="Pincode" FontSize="16" FontFamily="Helvetica-Light"/>
                                <Label TextColor="Red" Text="*" FontSize="16" FontFamily="Helvetica-Light"/>
                            </StackLayout>

                            <controls:RoundRectFrame HorizontalOptions="FillAndExpand" VerticalOptions="FillAndExpand" Padding="0" HeightRequest="40">
                                <StackLayout Orientation="Horizontal" Padding="1,0,10,0" BackgroundColor="Transparent">
                                    <xfx:XfxComboBox 
                                        Text="{Binding Pincode, Mode=TwoWay}" 
                                        FontSize="16"  
                                        FontFamily="Helvetica-Light" TextColor="Black"
                                        Keyboard="Numeric"
                                        FloatingHintEnabled="False"
                                        HorizontalOptions="FillAndExpand"
                                        VerticalOptions="FillAndExpand"
                                        ItemsSource="{Binding PinCodes}" 
                                        SortingAlgorithm="{Binding SortingAlgorithm}">
                                        <xfx:XfxComboBox.Behaviors>
                                            <local:MaxLengthValidatorBehavior x:Name="pincodeEntryLimit"/>
                                            <local:NumberValidationBehavior />
                                        </xfx:XfxComboBox.Behaviors>
                                    </xfx:XfxComboBox>
                                </StackLayout>
                            </controls:RoundRectFrame>

                        </StackLayout>
```
But expected behavior not working(Page not redirecting to next screen which contains ComboBox).
After removing Combo Box everything works correctly and redirecting to next page..

**Comment by ChaseFlorell** [comment]
do you have any errors you can give?

**Comment by NageshDegil** [comment]
[AddProductViewModel.zip](https://github.com/XamFormsExtended/Xfx.Controls/files/1426916/AddProductViewModel.zip)
@ChaseFlorell not getting any error message. Only issue is page not redirecting.

I did some more investigation to find error by replacing my MVVMLight ViewModel to given sample model at that time its working fine.

I don't getting whats the issue persist in code.[

](url)

**Comment by NageshDegil** [comment]
@ChaseFlorell  Can you please help to resolve the issue

**Comment by ChaseFlorell** [comment]
I'm not sure what to do with that `.cs` file. There's no reference to the controls in there.
Can you please post a repro of your issue on github? I can fork it and test.

**Comment by ChaseFlorell** [comment]
side note: your layout performance will be better with a Grid instead of nested StackLayouts

**Comment by ChaseFlorell** [comment]
This issue has been inactive for 10 days and I'm therefore closing. If you can provide a repro of your issue, we can definitely re-open
