### ISSUE TITLE
xfx:XfxEntry cast in EditText

### ISSUE THREAD

**Issue by akhiljain05** [XamFormsExtended/Xfx.Controls#34]
HI 
I am going to cast xfx:XfxEntry to EditText for show hide password but it gives me 
` <xfx:XfxEntry Placeholder="Password" IsPassword="true" Text="{Binding Password}">
                <xfx:XfxEntry.Effects>
                   <todo:ShowHidePassEffect />
               </xfx:XfxEntry.Effects>
            </xfx:XfxEntry>`

and casting code : -
`EditText editText = ((EditText)Control);`

It works fine if I use normal entity 

Please help me

**Comment by ChaseFlorell** [comment]
You should be able to access the `XfxEditor` within your effect. Alternatively (and I haven't tested this), what happens in you simply bind `IsPassword`?

```xml
<xfx:XfxEntry IsPassword="{Binding IsPassword}" />
```

```csharp
private bool _isPassword;
public bool IsPassword
{
    get { return _isPassword; }
    set {
        _isPassword = value;
        RaisePropertyChanged(nameof(IsPassword));
    }
}
```

**Comment by akhiljain05** [comment]
Ok i will try your recommendation and revert you back
