### ISSUE TITLE
Toolbar title set center align

### ISSUE THREAD

**Issue by akhiljain05** [XamFormsExtended/Xfx.Controls#35]
I am coding in Xamarin.Forms, What I supposed to align Toolbar title in the center in my portable project?

**Comment by ChaseFlorell** [comment]
I'm not sure what your question has to do with Xfx.Controls. Can you elaborate?
If you have a specific Forms related question, I suggest you ask it in their forums 
https://forums.xamarin.com/categories/xamarin-forms
