### ISSUE TITLE
Combo box Sorting Algorithm 

### ISSUE THREAD

**Issue by NageshDegil** [XamFormsExtended/Xfx.Controls#36]
### Expected Behavior
While trying to enter input into Combo Box,  Ideal it should predict related List even when I type single character.

### Actual Behavior
Combo Box not predicting for single character, for auto predict have to enter at least 2 characters. 

![photo_2017-11-23_17-16-58](https://user-images.githubusercontent.com/26921042/33171593-c042524c-d072-11e7-8fe3-31d6c7fd28ba.jpg)

![photo_2017-11-23_17-18-01](https://user-images.githubusercontent.com/26921042/33171594-c09a4402-d072-11e7-93de-3eeb7b23857f.jpg)

**Comment by ChaseFlorell** [comment]
Hey @NageshDegil, thanks for reaching out.
You can adjust how quickly the combobox kicks in by setting the `Threshold`

```csharp
var combo = new XfxComboBox{Threshold = 1};
```

```xml
<xfx:XfxComboBox Threshold="1" />
```
