### ISSUE TITLE
How to change the placeholder text size in xfxentry

### ISSUE THREAD

**Issue by hashimks** [XamFormsExtended/Xfx.Controls#39]
I am using the latest stable version. Two issues i am facing now are

1. I did not find any property for setting the size of placeholder text. I can set the input text size but not the placeholder text.

2. I need to change the underline color of the entry as it is default taking the color used to tint the widgets which i need to be a different one. 

Can you please help me?

**Comment by ChaseFlorell** [comment]
1) is a duplicate of #27 
2) has been solved in yesterday's 1.1.0 release

Setting the Active color is now done via

```xml
<xfx:XfxEntry ActivePlaceholderColor="#ff0000" />
```

**Comment by hashimks** [comment]
Thanks :) 👍 . I took the developer build and its working
