### ISSUE TITLE
XfxEntry not masking when IsPassword=true in Xamarin.Forms Android

### ISSUE THREAD

**Issue by rmawani** [XamFormsExtended/Xfx.Controls#4]
## Bug 
There seems to be a bug within XfxEntry, whereby the control will not mask input when `IsPassword=true` in Xamarin.Forms Android.

* Version Number of Control: 1.0.0.2
* Device Tested On: Samsung Galaxy S5 (Android 6.0) and S6 (Android 7.0)
* Simulator Tested On: Nexus 5 (Android 6.0) and Nexus 6 (Android 7.0)

### Expected Behavior
XfxEntry Control should mask the field when the `IsPassword` property is set to `true`.

### Actual Behavior
No masking of the field occurs

### Steps to reproduce the Behavior
Using C# (not XAML), create a simple screen with a Password entry field and set the `IsPassword` property to `true`.

**Comment by ChaseFlorell** [comment]
Good catch. Is this blocking you? I think I can look at it in the next day or so.

**Comment by rmawani** [comment]
Thanks for the great control, by the way!

Although it is blocking me somewhat, I can live with it for the time being until you're able to get around to fixing it in the next few days.

Thanks again!

**Comment by ChaseFlorell** [comment]
Fixed in commit b703f65

**Comment by ChaseFlorell** [comment]
@rmawani feel free to head over to Nuget and grab the latest build 😄

**Comment by rmawani** [comment]
Thanks for the fix, Chase... The masking works perfectly and as advertised in your Example app. However, when I build my own app with the latest build (1.0.1.3) of Xfx.Controls, I still have no masking.

I figured it might be because I've implemented the control in a Shared project environment as opposed to PCL, so I created a bare-bones PCL Solution and dropped an XfxEntry control onto the default ContentPage and added `IsPassword = true`. I then ran this completely unmodified Solution in the Emulator and surprisingly, no masking on the control.

I'm completely stumped and can only think it must be something somewhere in my config settings.

Any thoughts? Maybe you can create a bare-bones PCL Solution on your end, drop in a, XfxEntry control and then revert back with your findings?

**Comment by ChaseFlorell** [comment]
Well it's entirely my fault (PEBKAC)... As A result, I've opened issue #5 and also uploaded build 1.0.1.4 to nuget (which will be live shortly) Please test that version.

I did all of my testing in debug mode and forgot to create a release build. I'm so used to using build scripts that I didn't even think of it when I created that package (which re-used the old 1.0.0.2 build)

Whoops!

**Comment by rmawani** [comment]
Thanks again, Chase! 

As much as the password masking issue is resolved, it seems like the fix may have introduced another weird bug that suppresses any text that is pre-loaded into the `Text` Property at runtime. For example, during testing, let's say I would like to pre-populate the XfxEntry with the User's email address instead of having to re-type it every time. This text does not show up on an Android build whereas it did before I applied the  package update. iOS seems fine...

Can you please verify if this happens on your end as well?

Thanks again!

**Comment by ChaseFlorell** [comment]
@rmawani is this still only Android?

**Comment by ChaseFlorell** [comment]
@rmawani, I think I have a fix but I don't want to risk another crappy upload to nuget. Can you test from here? If you're satisfied, I'll publish to nuget.

https://github.com/XamFormsExtended/Xfx.Controls/releases/tag/1.0.2

**Comment by rmawani** [comment]
Thanks for the fix, @ChaseFlorell. This one works as expected!

Thanks again!
