### ISSUE TITLE
XfxCardView Tapping

### ISSUE THREAD

**Issue by Mushtaq123** [XamFormsExtended/Xfx.Controls#42]
Please fill out either the bug or feature request section and remove whatever section you are not using.

# Bug 

* Version Number of Control:
* Device Tested On **Samsung, Moto G3**
* Simulator Tested On **Android Nexus, iPhone 8 Plus**

### Affects

- [x] iOS
- [x] Android

### Expected Behavior
 Tap Gesture over Cardview on listview tapping should be working

### Actual Behavior
 Tap Gesture over Cardview on listview tapping is not working

**Comment by ChaseFlorell** [comment]
@Mushtaq123 go ahead and test the latest release.
