### ISSUE TITLE
XfxEntry HorizontalTextAlignment End

### ISSUE THREAD

**Issue by OmarHassan25** [XamFormsExtended/Xfx.Controls#43]
In XfxEntry HorizontalTextAlignment End the error message remains on the Start side and not flipped to be end aligned, Any help?

`     <xfx:XfxEntry Grid.Row="1"
                HorizontalTextAlignment="End"
                          Grid.Column="1"
                          Placeholder="أكتب اسمك"
                          Text="{Binding Name}"
                          ErrorText="خطأ" />`

**Comment by ChaseFlorell** [comment]
oh that's a good question. Are you looking to be able to do RTL or just align right?
