### ISSUE TITLE
How can I do word wrap in xfxEntry ?

### ISSUE THREAD

**Issue by Nishita1121** [XamFormsExtended/Xfx.Controls#48]
* Version Number of Control:  1.1.3
* Device Tested On: Android and I phone
* Simulator Tested On: 

### Affects

- [ ] iOS
- [ ] Android

Input  text given in xfxEntry is  not wrapping to the next line. Is there any property similar to line break mode like in labels ?

Please suggest some solution to slove this issue.

**Comment by ChaseFlorell** [comment]
Whoah, I'm not sure how I missed your question, sorry.
The Entry is only a single line by design. What you want is an Editor, unfortunately I have yet to build an `XfxEditor` that will support floating labels.
