### ISSUE TITLE
Feature: XfxEntry line color property

### ISSUE THREAD

**Issue by quantumarun** [XamFormsExtended/Xfx.Controls#52]
Please fill out either the bug or feature request section and remove whatever section you are not using.
Need property to change the color of Entry Line(Line below the Text Entered) on Android. Currently on dark background the entry field on android is almost invisible.

# Bug 

* Version Number of Control:
* Device Tested On:
* Simulator Tested On:

### Affects

- [ ] iOS
- [x] Android

### Link to Github Reproduction (optional but recommended)

[Repro]()

# Feature Request:
Please fill in what you would like

**Comment by ChaseFlorell** [comment]
Try setting your placeholder color and let me know how it goes.

**Comment by quantumarun** [comment]
Great. That seems to solve my issue :).
