### ISSUE TITLE
Current Text value gets lost when model properties are already populated.

### ISSUE THREAD

**Issue by dphable** [XamFormsExtended/Xfx.Controls#7]
Please fill out either the bug or feature request section and remove whatever section you are not using.

## Bug 

* Version Number of Control: 1.0.1.4
* Device Tested On: Nexus 6P
* Simulator Tested On: n/a

### Expected Behavior
Model property values are displayed in XfxEntry control upon page load.

### Actual Behavior
Model property values are not displayed.

### Steps to reproduce the Behavior
In the example app -> MainPage constructor...

        public MainPage()
        {
            Model = new MainPageModel();
            Model.Name = "Chase";
            BindingContext = Model;

            InitializeComponent();
        }

In MainPage.xaml, remove...

    <ContentPage.BindingContext>
        <app:MainPageModel />
    </ContentPage.BindingContext>

In XfxEntryRendererDroid.OnElementChanged(), calling SetText() before SetInputType() seems to resolve the issue.

**Comment by ChaseFlorell** [comment]
Thanks for the report @dphable. Can you try V1.0.2 from Nuget? I think this is solved.

**Comment by ChaseFlorell** [comment]
Note, there is discussion about this here
https://github.com/XamFormsExtended/Xfx.Controls/issues/4#issuecomment-287664800

**Comment by dphable** [comment]
Yes, it is working now.  Thanks!
