### ISSUE TITLE
 After updating xamarin forms 4.0 stopped working on ios

### ISSUE THREAD

**Issue by michel7siqueira** [XamFormsExtended/Xfx.Controls#81]
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Xamarin\iOS\Xamarin.iOS.Common.targets(795,3): error MT2101: Can't resolve the reference 'System.Void Xamarin.Forms.Platform.iOS.VisualElementTracker::.ctor(Xamarin.Forms.Platform.iOS.IVisualElementRenderer)', referenced from the method 'System.Void Xfx.Controls.iOS.XfxVisualElementManager::Init(Xamarin.Forms.Platform.iOS.IVisualElementRenderer,Xamarin.Forms.Platform.iOS.VisualElementRendererFlags)' in 'Xamarin.Forms.Platform.iOS, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'.

**Comment by DeShrike** [comment]
Any news on this ?
I have the same issue with version v4.0.0.94569-pre3

**Comment by uzairali001** [comment]
Why would you want to use Xfs.Controls with Xamarin 4.0 if it already has Material design controls just change visual to Material on Content page

**Comment by mrbelk** [comment]
I'm actually getting this same error with Xamarin.Forms 3.5 when building on MS App Center.

**Comment by mrbelk** [comment]
For what it's worth, I cannot get the new material entry effects when using XF4.0-pre4 on iOS.

**Comment by ChaseFlorell** [comment]
It sounds like there is some effort required to get everything working with Pie and Forms 4. It's just super hard for me to find the cycles to look into all of this right now. Let me see what I can come up with.

**Comment by mrbelk** [comment]
Chase, It's iOS we're talking about here, not Android.

**Comment by ChaseFlorell** [comment]
Yep, that was meant as a blanket statement, sorry for the confusion.
I need to put effort into getting this thing working properly in Android (Pie) and also get it working properly in Android AND iOS for Xamarin Forms 4.

**Comment by mrbelk** [comment]
10-4. Also, my experience is that this iOS issue only affects signed device builds, not simulator ones

Matthew Belk
BizSpeed, Inc
678-287-3315

________________________________

**Comment by arvindrajachourasiya** [comment]
Me too facing issue................

**Comment by michel7siqueira** [comment]
Reso
