### ISSUE TITLE
XfxCombobox =>suggestion not showing when user enter only single character

### ISSUE THREAD

**Issue by sarthak199526** [XamFormsExtended/Xfx.Controls#85]
Please fill out either the bug or feature request section and remove whatever section you are not using.

# Bug  Hi Suggestion list not showing for combobox when user enter only single character . It starts to show when minimum character are two inside combobox But I want to show suggestion list even on single character entered by user . Is there any property to set minimum number of character that I can set it to 1 ;

* Version Number of Control:
* Device Tested On:
* Simulator Tested On:

### Affects

- [x] iOS
- [x] Android

### Link to Github Reproduction (optional but recommended)

[Repro]()

# Feature Request:
Please fill in what you would like

**Comment by ChaseFlorell** [comment]
you'll want to use the `Threshold` property.

https://github.com/XamFormsExtended/Xfx.Controls/blob/master/src/Xfx.Controls/XfxComboBox.cs#L31

**Comment by SagarPanwala** [comment]
@ChaseFlorell  : This is closed one and I probably should ask new, but my question is similar to this one.
I want to show some records by default on entry focus without typing anything. I tried Threshold 0 and -1, but it didn't work.

**Comment by sarthak199526** [comment]
@ChaseFlorell  take the code and add your specific condition
