### ISSUE TITLE
IsEnabled not working for XfxEntry

### ISSUE THREAD

**Issue by sander1133** [XamFormsExtended/Xfx.Controls#9]
## Bug 

* Version Number of Control: 1.0.2.0
* Device Tested On: Samsung Galaxy S6
* Simulator Tested On: Any android

### Expected Behavior

Changing IsEnabled to False will update the Entry to a disabled state

### Actual Behavior

Field is still enabled

### Steps to reproduce the Behavior

Try set IsEnabled to False

## Feature Request:

Update Render so it will listen to IsEnabled updates

Kind regards,
Sander

**Comment by ChaseFlorell** [comment]
I've submitted a possible fix a89b57e499df28655cc77be9ae75a0a370b7c192

Is there any way for you to test this without me creating a new release? 

_note: you can create a build from your powershell command line by running_

```powershell
> .\build.ps1 -BuildVersion 1.0.3.6
```
