### ISSUE TITLE
Maxlength is not working on XfxEntry 

### ISSUE THREAD

**Issue by sagarmp02** [XamFormsExtended/Xfx.Controls#99]
Please fill out either the bug or feature request section and remove whatever section you are not using.

# Bug 

* Version Number of Control:
* Device Tested On:
* Simulator Tested On:

### Affects

- [ ] iOS
- [ ] Android

### Link to Github Reproduction (optional but recommended)

[Repro]()

# Feature Request:
Please fill in what you would like

**Comment by ChaseFlorell** [comment]
No details
